services:
  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./producer
    container_name: producer
    environment:
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./producer:/app

  consumer:
    build: ./consumer
    container_name: consumer
    restart: always
    environment:
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./consumer:/app
