services:
  auth:
    build:
      context: ../../
      dockerfile: src/docker/dfiles/producer
    container_name: auth
    env_file:
      - ../.env
    environment:
      - RABBITMQ_HOST=amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./producer:/app
    networks:
      - shared_network

  email:
    build:
      context: ../../
      dockerfile: src/docker/dfiles/consumer
    container_name: email
    env_file:
      - ../.env
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./consumer:/app
    networks:
      - shared_network

networks:
  shared_network:
